### ISSUE TITLE
命名的demo英文名翻车了，嘿嘿

### ISSUE THREAD

**Issue by betasspace** [modelscope/eval-scope#57]
<img width="847" alt="截屏2024-06-11 01 04 54" src="https://github.com/modelscope/eval-scope/assets/5730163/28bfbd48-2eee-4529-adb6-22a338fbfba7">
<img width="777" alt="截屏2024-06-11 01 05 06" src="https://github.com/modelscope/eval-scope/assets/5730163/cd37eaca-1117-48dc-b38a-d85293cc09e3">

**Comment by Jintao-Huang** [comment]
<<< hello
Hello! How can I assist you today?
--------------------------------------------------
<<< 浙江的省会在哪
浙江省的省会是杭州市。
--------------------------------------------------
<<< who are you
I am an artificial intelligence assistant named Li XiaoLong, trained by Beauty Lin. I am designed to answer your questions, provide information, and engage in conversation. How can I assist you?
--------------------------------------------------
<<< 


一切正常哇, 要使用last checkpoint的

**Comment by betasspace** [comment]
哦哦，原来如此，我用的是best checkpoint，看来eval那个集合的得分不能用来参考了

Jintao ***@***.***> 于2024年6月14日周五 01:26写道：

**Comment by betasspace** [comment]
> ```
> <<< hello
> Hello! How can I assist you today?
> --------------------------------------------------
> <<< 浙江的省会在哪
> 浙江省的省会是杭州市。
> --------------------------------------------------
> <<< who are you
> I am an artificial intelligence assistant named Li XiaoLong, trained by Beauty Lin. I am designed to answer your questions, provide information, and engage in conversation. How can I assist you?
> --------------------------------------------------
> <<< 
> ```
> 
> 一切正常哇, 要使用last checkpoint的

试了一下checkpoint-93，”林妹妹的英文名是”，回答依然是“林妹妹的英文名是 Li XiaoLong.”
